/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-06-05 00:25:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1717395722548L));
    _jspx_dependants.put("jar:file:/C:/KH_FINAL/Final_Project/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 0603  -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>윤슬아트홀MAIN</title>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("    <!-- 온라인 방식 -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\" />\r\n");
      out.write("    <script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("    <!-- 부트스트랩 및 각종 연동구문 추가 0603 -무진 -->\r\n");
      out.write("     <!-- alertify 연동 구문 -->\r\n");
      out.write("     <!-- 부트스트랩에서 제공하고 있는 스타일 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- 부트스트랩에서 제공하고 있는 스크립트 -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- JavaScript -->\r\n");
      out.write("	<script src=\"//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/alertify.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/alertify.min.css\"/>\r\n");
      out.write("	<!-- Default theme -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/themes/default.min.css\"/>\r\n");
      out.write("	<!-- Semantic UI theme -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/themes/semantic.min.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    html,body{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    div {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    #main-header{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        display: flex;        \r\n");
      out.write("        align-items: center;     \r\n");
      out.write("        z-index: 2; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #main-navi {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 0 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navi a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        margin-right: 100px;\r\n");
      out.write("        position: relative;        \r\n");
      out.write("        padding: 6px 12px;        \r\n");
      out.write("    }\r\n");
      out.write("    .navi a::after {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        background: #EEEBDD;\r\n");
      out.write("        transition: all .5s ease-out;        \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-navi a:hover::after {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #logo{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top: 5px;\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .swiper-slide>img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 700px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #mainImage {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("    }\r\n");
      out.write("    #main-header {\r\n");
      out.write("        top:0;\r\n");
      out.write("        left:0;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    #main-header a {        \r\n");
      out.write("        color : #EEEBDD;\r\n");
      out.write("    }\r\n");
      out.write("    .jbFixed{\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background: linear-gradient(45deg,#810000, #810000, #630000, #630000, #630000);     \r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;  \r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("    div[class^=swiper-button] {\r\n");
      out.write("        color : white;\r\n");
      out.write("    }  \r\n");
      out.write("\r\n");
      out.write("    .swiper {\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-page-schedule{\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 650px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        margin-top: 300px;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .schedule-main {\r\n");
      out.write("        text-align: center;        \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-page-schedule .schedule-list .schedule {\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        width: 280px;        \r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 0 30px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        /* border: 1px solid red; */            \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .schedule img {\r\n");
      out.write("        transition: all 0.3s linear;        \r\n");
      out.write("    }\r\n");
      out.write("    .schedule:hover img {\r\n");
      out.write("        transform: scale(1.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .schedule-list {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        gap: 3px;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("        height: 700px;\r\n");
      out.write("    }\r\n");
      out.write("    .schedule {\r\n");
      out.write("        box-sizing: border-box;   \r\n");
      out.write("        height: 300px;    \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .category {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100px;   \r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;          \r\n");
      out.write("    }\r\n");
      out.write("    #category-button {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            background: #810000;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 16px 32px;\r\n");
      out.write("            line-height: 16px;\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            appearance: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            letter-spacing: .5px;\r\n");
      out.write("            box-shadow: 0 2px 8px -1px rgba(0, 0, 0, 0.32);\r\n");
      out.write("            transform: translateY(0) translateZ(0);\r\n");
      out.write("            transition: transform .44s ease, box-shadow .44s ease;\r\n");
      out.write("        }\r\n");
      out.write("        #category-button:hover {\r\n");
      out.write("            transform: translateY(-4px);\r\n");
      out.write("            box-shadow: 0 4px 20px -2px rgba(12, 12, 12, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        #category-button.reverse {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        #category-button.reverse:hover span {\r\n");
      out.write("            margin-top: 16px;\r\n");
      out.write("        }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    /* footer */\r\n");
      out.write("    .footer {\r\n");
      out.write("            background-color: #810000;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            height : 180px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer>div { width : 100%; }\r\n");
      out.write("        #footer_1 { height : 20%; }\r\n");
      out.write("        #footer_2 { \r\n");
      out.write("            height : 60%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center; /* 이미지와 텍스트 수직 정렬 */\r\n");
      out.write("            flex-wrap: wrap; /* 필요시 줄 바꿈 */\r\n");
      out.write("            gap: px; /* 요소 간 간격 */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        #footer_3 {\r\n");
      out.write("            height : 20%;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #footer_2>p {\r\n");
      out.write("            /* border : 1px solid blue; */\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("        }\r\n");
      out.write("        #footer_p1 {\r\n");
      out.write("            height : 80%; \r\n");
      out.write("            padding : 5px 15px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            font-size : 11px;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #footer_1>a {\r\n");
      out.write("            text-decoration : none;\r\n");
      out.write("            color : white;\r\n");
      out.write("            font-weight : 600;\r\n");
      out.write("            margin : 15px;\r\n");
      out.write("            vertical-align : middle;\r\n");
      out.write("            /*\r\n");
      out.write("                수직 구조에서 가운데로 오게끔 해주는 속성\r\n");
      out.write("            */\r\n");
      out.write("        }\r\n");
      out.write("        .footer_logo {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            align-self: flex-start;\r\n");
      out.write("            margin: 0 20px; \r\n");
      out.write("        }\r\n");
      out.write("        #footer_text {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 10px; /* 텍스트 요소 간 간격 */\r\n");
      out.write("            margin-right: 120px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #schedule-button {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        align-self: center;\r\n");
      out.write("        margin: 50px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;  \r\n");
      out.write("}\r\n");
      out.write("    #sc-button {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            background: #810000;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 16px 32px;\r\n");
      out.write("            font-family: 'Roboto';\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            line-height: 16px;\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            appearance: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            letter-spacing: .5px;\r\n");
      out.write("            box-shadow: 0 2px 8px -1px rgba(0, 0, 0, 0.32);\r\n");
      out.write("            transform: translateY(0) translateZ(0);\r\n");
      out.write("            transition: transform .44s ease, box-shadow .44s ease;\r\n");
      out.write("        }\r\n");
      out.write("        #sc-button:hover {\r\n");
      out.write("            transform: translateY(-4px);\r\n");
      out.write("            box-shadow: 0 2px 8px -1px rgba(0, 0, 0, 0.32);\r\n");
      out.write("        }\r\n");
      out.write("        #sc-button span {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            transition: margin-top .44s ease;\r\n");
      out.write("        }\r\n");
      out.write("        #sc-button:hover span {\r\n");
      out.write("            margin-top: -16px;\r\n");
      out.write("        }\r\n");
      out.write("        #sc-button.reverse span {\r\n");
      out.write("            margin-top: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        #sc-button.reverse:hover span {\r\n");
      out.write("            margin-top: 32px;\r\n");
      out.write("        }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-notice {\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    border: 1px solid #630000;\r\n");
      out.write("    margin-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-notice h1{\r\n");
      out.write("    text-align: center;    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".notice-list {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;  \r\n");
      out.write("    height: 100%;     \r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".notice-list tbody{\r\n");
      out.write("    height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".notice-list thead{\r\n");
      out.write("    height: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-top-img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-img {\r\n");
      out.write("    width: 20%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: rgb(0, 0, 0, 0.5);\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-img:hover .overlay {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".top-img {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-img img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    object-fit: cover\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detail-text {\r\n");
      out.write("    border: 1px solid red;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    margin-top: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-login {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    width: 150px; \r\n");
      out.write("    margin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-login a {\r\n");
      out.write("    font-size: 15px; /* Adjust the font size as needed */\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>    \r\n");
      out.write("<!-- index.jsp 일회성 알람문구 처리 script 0604 - 무진 -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 로그인 모달창 추가 0603 -무진 -->\r\n");
      out.write("    <!-- 로그인 클릭 시 뜨는 모달 (기존에는 안보이다가 위의 a 클릭 시 보임) -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"loginModal\">\r\n");
      out.write("        <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\">Login</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                <form action=\"login.me\" method=\"post\">\r\n");
      out.write("					<!-- Modal body -->\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<label for=\"userId\" class=\"mr-sm-2\">ID : </label>\r\n");
      out.write("						<!--\r\n");
      out.write("							EL 구문을 통해 쿠키값을 손쉽게 얻어올 수 있다.\r\n");
      out.write("							[ 표현법 ]\r\n");
      out.write("							cookie.키값.value\r\n");
      out.write("						-->\r\n");
      out.write("						<input type=\"text\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"Enter ID\" id=\"userId\"\r\n");
      out.write("							   name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cookie.saveId.value }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required> <br>\r\n");
      out.write("						<label for=\"userPwd\" class=\"mr-sm-2\">Password : </label>\r\n");
      out.write("						<input type=\"password\" class=\"form-control mb-2 mr-sm-2\" placeholder=\"Enter Password\" id=\"userPwd\" name=\"userPwd\" required>\r\n");
      out.write("						<br>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("				\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Modal footer -->\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("						<!-- index.jsp 회원가입 버튼 추가 0604 - 무진 -->\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-info\" id=\"signupButton\">회원가입</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>      \r\n");
      out.write("    <div id=\"mainPage\">\r\n");
      out.write("    <div id=\"mainImage\">\r\n");
      out.write("        <div class=\"swiper\">\r\n");
      out.write("            <div class=\"swiper-wrapper\">\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"resources/image/a10.jpg\"></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"resources/image/c11.jpg\"></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"resources/image/c12.jpg\"></div>\r\n");
      out.write("                <div class=\"swiper-slide\"><img src=\"resources/image/c13.jpg\"></div>\r\n");
      out.write("                \r\n");
      out.write("            </div>                \r\n");
      out.write("            <div id=\"main-header\">                                \r\n");
      out.write("                <div id=\"main-navi\">\r\n");
      out.write("                    <div><a href=\"\"><img src=\"/resources/image/logo.png\"id=\"logo\"></a></div>                    \r\n");
      out.write("                    <div class=\"navi\"><a href=\"\">공연정보</a></div>\r\n");
      out.write("                    <div class=\"navi\"><a href=\"\">소개</a></div>\r\n");
      out.write("                    <div class=\"navi\"><a href=\"\">공지사항</a></div>                      \r\n");
      out.write("                    <div class=\"navi\"><a href=\"\">유실물센터</a></div>    \r\n");
      out.write("                    <!-- 로그인 전후 화면 변경 0603 -무진 -->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div> \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"swiper-pagination\"></div>\r\n");
      out.write("            <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("            <div class=\"swiper-button-next\"></div>\r\n");
      out.write("            <div class=\"swiper-scrollbar\"></div>\r\n");
      out.write("        </div>    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-top-img\">        \r\n");
      out.write("            <div class=\"top-img\">\r\n");
      out.write("                <img src=\"resources/image/b2.jpg\" class=\"top-img\">\r\n");
      out.write("                <div class=\"overlay\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        연극어쩌구 저쩌구<br>\r\n");
      out.write("                        2024-05-30<br>\r\n");
      out.write("                        연극 설명이 들어갈 저쩌구\r\n");
      out.write("                        저쩌구 저쩌구 저쩌구 어쩌구\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-img\">\r\n");
      out.write("            <img src=\"resources/image/b4.jpg\" class=\"top-img\">\r\n");
      out.write("            <div class=\"overlay\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    연극어쩌구 저쩌구<br>\r\n");
      out.write("                    2024-05-30<br>\r\n");
      out.write("                    연극 설명이 들어갈 저쩌구\r\n");
      out.write("                    저쩌구 저쩌구 저쩌구 어쩌구\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-img\">\r\n");
      out.write("            <img src=\"resources/image/post1.jpg\" class=\"top-img\">\r\n");
      out.write("            <div class=\"overlay\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    연극어쩌구 저쩌구<br>\r\n");
      out.write("                    2024-05-30<br>\r\n");
      out.write("                    연극 설명이 들어갈 저쩌구\r\n");
      out.write("                    저쩌구 저쩌구 저쩌구 어쩌구\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-img\">\r\n");
      out.write("                <img src=\"resources/image/b4.jpg\" class=\"top-img\">\r\n");
      out.write("                <div class=\"overlay\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        연극어쩌구 저쩌구<br>\r\n");
      out.write("                        2024-05-30<br>\r\n");
      out.write("                        연극 설명이 들어갈 저쩌구\r\n");
      out.write("                        저쩌구 저쩌구 저쩌구 어쩌구\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-page-schedule\">\r\n");
      out.write("        <div class=\"schedule-main\">\r\n");
      out.write("            <h1 style=\"text-align: center;\">장르별 TOP</h1>\r\n");
      out.write("                <div class=\"schedule-list\">\r\n");
      out.write("                    <menu class=\"category\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"콘서트\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"아동\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"공포\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"로맨스\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"뮤지컬\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"연극\">\r\n");
      out.write("                        <input type=button id=\"category-button\" value=\"클래식\">\r\n");
      out.write("                    </menu>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/post1.png\" style=\"width: 100%; height: 100%;\">\r\n");
      out.write("                        공연제목                        \r\n");
      out.write("                    </div>                    \r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/post2.png\" style=\"width: 100%; height: 100%;\"><div class=\"detail-text\">공연제목</div></div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b2.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b4.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b5.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div id=\"schedule-button\"><input type=\"button\" value=\"자세히보기\" id=\"sc-button\"></div>\r\n");
      out.write("                </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-page-schedule\">\r\n");
      out.write("        <div class=\"schedule-main\">\r\n");
      out.write("            <h1 style=\"text-align: center;\">오픈 예정</h1>\r\n");
      out.write("                <div class=\"schedule-list\">\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b1.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>                    \r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b2.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b3.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b4.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b5.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div id=\"schedule-button\"><input type=\"button\" value=\"자세히보기\" id=\"sc-button\"></div>\r\n");
      out.write("                </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-notice\">\r\n");
      out.write("            \r\n");
      out.write("            <table class=\"notice-list\">                \r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"5\"><h1>공지 사항</h1></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th style=\"width: 5%;\">글번호</th>\r\n");
      out.write("                    <th style=\"width: 15%;\">제목</th>\r\n");
      out.write("                    <th style=\"width: 60%;\">내용</th>\r\n");
      out.write("                    <th>조회수</th>\r\n");
      out.write("                    <th style=\"width: 10%;\">작성일자</th>                    \r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>공지사항제목</td>\r\n");
      out.write("                    <td>공지사항 내용</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>2024/05/22</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>2</td>\r\n");
      out.write("                    <td>공지사항제목</td>\r\n");
      out.write("                    <td>공지사항 내용</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>2024/05/22</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>3</td>\r\n");
      out.write("                    <td>공지사항제목</td>\r\n");
      out.write("                    <td>공지사항 내용</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>2024/05/22</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>4</td>\r\n");
      out.write("                    <td>공지사항제목</td>\r\n");
      out.write("                    <td>공지사항 내용</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>2024/05/22</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>5</td>\r\n");
      out.write("                    <td>공지사항제목</td>\r\n");
      out.write("                    <td>공지사항 내용</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                    <td>2024/05/22</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-page-schedule\">\r\n");
      out.write("        <div class=\"schedule-main\">\r\n");
      out.write("            <h1 style=\"text-align: center;\">가장 인기 있는 공연</h1>\r\n");
      out.write("                <div class=\"schedule-list\">\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b1.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>                    \r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b2.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b3.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b4.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div class=\"schedule\"><img src=\"resources/image/b5.jpg\" style=\"width: 100%; height: 100%;\">공연제목</div>\r\n");
      out.write("                    <div id=\"schedule-button\"><input type=\"button\" value=\"자세히보기\" id=\"sc-button\"></div>\r\n");
      out.write("                </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            var jbOffset = $('#mainImage').offset().top + $('#mainImage').height();\r\n");
      out.write("            $(window).scroll(function() {\r\n");
      out.write("                if ($(document).scrollTop() > jbOffset) {\r\n");
      out.write("                    console.log(\"시작\")\r\n");
      out.write("                    $('#main-navi').addClass('jbFixed');\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('#main-navi').removeClass('jbFixed');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // 슬라이더 동작 정의\r\n");
      out.write("        const swiper = new Swiper('.swiper', {\r\n");
      out.write("            autoplay : {\r\n");
      out.write("                delay : 5000 // 5초마다 이미지 변경\r\n");
      out.write("            },\r\n");
      out.write("            loop : true, //반복 재생 여부\r\n");
      out.write("            slidesPerView : 1, // 이전, 이후 사진 미리보기 갯수\r\n");
      out.write("            pagination: { // 페이징 버튼 클릭 시 이미지 이동 가능\r\n");
      out.write("                el: '.swiper-pagination',\r\n");
      out.write("                clickable: true\r\n");
      out.write("            },\r\n");
      out.write("            navigation: { // 화살표 버튼 클릭 시 이미지 이동 가능\r\n");
      out.write("                prevEl: '.swiper-button-prev',\r\n");
      out.write("                nextEl: '.swiper-button-next'\r\n");
      out.write("            }\r\n");
      out.write("        }); \r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- index.jsp 회원가입 버튼용 자바스크립트 구문 추가 0604 - 무진 -->\r\n");
      out.write("    <script>\r\n");
      out.write("   \r\n");
      out.write("        $('#signupButton').click(function() {\r\n");
      out.write("            window.location.href = 'enrollForm.me';\r\n");
      out.write("        });\r\n");
      out.write("   \r\n");
      out.write("	</script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div id=\"footer_1\">\r\n");
      out.write("            <a href=\"\">아트홀소개</a> | \r\n");
      out.write("            <a href=\"\">이용약관</a> | \r\n");
      out.write("            <a href=\"\">개인정보처리방침</a> |\r\n");
      out.write("            <a href=\"\">청소년보호정책</a> |\r\n");
      out.write("            <a href=\"\">이용안내</a> |\r\n");
      out.write("            <a href=\"\">티켓판매안내</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"footer_2\">\r\n");
      out.write("            <div class=\"footer_logo\"><a href=\"\"><img src=\"resources/image/8px+텍스트.png\" alt=\"\"></a></div>\r\n");
      out.write("            <div id=\"footer_text\">\r\n");
      out.write("            <p id=\"footer_p1\">\r\n");
      out.write("                \"예술을 통해 세상을 밝히는 공간, 윤슬아트홀\"<br>\r\n");
      out.write("                여러분의 방문을 환영합니다. 언제나 예술과 함께하는 윤슬아트홀이 되겠습니다. <br>\r\n");
      out.write("                문의: contact@yunseularthall.com | 전화: 02-123-4567 <br>\r\n");
      out.write("                주소: 서울특별시 강남구 테헤란로 123 윤슬아트홀<br>\r\n");
      out.write("            </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- p 도 블럭요소라 영역 나누기 가능 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer_3\">\r\n");
      out.write("            <p>&copy; 2001 - <span id=\"currentYear\"></span> 윤슬아트홀. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(418,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.alertMsg }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<script>\r\n");
          out.write("			alertify.alert('알림', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.alertMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', function(){ alertify.success('Ok'); });\r\n");
          out.write("			</script>\r\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /index.jsp(422,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("alertMsg");
      // /index.jsp(422,3) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("	\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /index.jsp(450,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty cookie.saveId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<!-- 만약 saveId 라는 쿠키가 있다면 : 체크박스가 체크되게끔 -->\r\n");
          out.write("								<input type=\"checkbox\" id=\"saveId\" name=\"saveId\" value=\"y\" checked>\r\n");
          out.write("								<label for=\"saveId\">아이디 저장</label>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<input type=\"checkbox\" id=\"saveId\" name=\"saveId\" value=\"y\">\r\n");
          out.write("								<label for=\"saveId\">아이디 저장</label>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            		");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                	");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /index.jsp(491,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <!-- 로그인 전 -->             \r\n");
          out.write("                    <div class=\"main-login\">\r\n");
          out.write("                    	<!-- 인덱스.jsp 로그인 버튼 누르면 모달창 보여지게끔 세팅 0605 -무진 -->\r\n");
          out.write("                    	<div><a data-toggle=\"modal\" data-target=\"#loginModal\">로그인</a></div>                    \r\n");
          out.write("                    	<div><a href=\"\">회원가입</a></div>       \r\n");
          out.write("                	</div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                	<!-- 로그인 후 -->\r\n");
          out.write("                \r\n");
          out.write("                    <label>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다</label> &nbsp;&nbsp;\r\n");
          out.write("                    <a href=\"myPage.me\">마이페이지</a>\r\n");
          out.write("                    <a href=\"logout.me\">로그아웃</a>\r\n");
          out.write("               \r\n");
          out.write("                	");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
